pid /var/run/nginx/nginx.pid;
worker_processes  1;

events {
  worker_connections  1024;
}

http {
  client_body_temp_path /var/tmp/nginx/client_body;
  proxy_temp_path       /var/tmp/nginx/proxy;
  fastcgi_temp_path     /var/tmp/nginx/fastcgi;
  uwsgi_temp_path       /var/tmp/nginx/uwsgi;
  scgi_temp_path        /var/tmp/nginx/scgi;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;
  server {
    listen 3000;
    server_name  localhost;
    server_tokens off;

    root   /usr/share/nginx/html;
    index  index.html index.htm;
    include /etc/nginx/mime.types;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location /v1/esignet {
      proxy_pass         http://esignet:8088/v1/esignet;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
    }
    location /.well-known/openid-configuration {
      proxy_pass         http://esignet:8088/v1/esignet/oidc/.well-known/openid-configuration;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
    }
    location /.well-known/jwks.json {
      proxy_pass         http://esignet:8088/v1/esignet/oauth/.well-known/jwks.json;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
    }
    location /.well-known/oauth-authorization-server {
      proxy_pass         http://esignet:8088/v1/esignet/oauth/.well-known/oauth-authorization-server;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
    }
    location /.well-known/openid-credential-issuer {
      proxy_pass         http://esignet:8088/v1/esignet/vci/.well-known/openid-credential-issuer;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
    }
    location /static/js/ {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
    location /static/css/ {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
    location /locales/ {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
    location /theme/ {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
    location /images/ {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
    location = /logo.png {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /local/totp/ {
      proxy_pass         http://host.docker.internal:8099/local/totp/;
      proxy_redirect     off;
      proxy_read_timeout 90s;
      proxy_connect_timeout 10s;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
