FROM nginx:1.28.0-alpine3.21-slim

ARG SOURCE
ARG COMMIT_HASH
ARG COMMIT_ID
ARG BUILD_TIME
LABEL source=${SOURCE}
LABEL commit_hash=${COMMIT_HASH}
LABEL commit_id=${COMMIT_ID}
LABEL build_time=${BUILD_TIME}

RUN apk add --no-cache zip curl

ENV base_path=/usr/share/nginx/html/artifactory
ENV i18n_zip_path=${base_path}/libs-release-local/i18n
ENV theme_zip_path=${base_path}/libs-release-local/theme
ENV image_zip_path=${base_path}/libs-release-local/image
ENV work_dir=/work

COPY src/ ${work_dir}/src/
COPY configure-esignet-ui-assets.sh /configure-esignet-ui-assets.sh
COPY nginx-esignet-ui-assets.conf /etc/nginx/conf.d/default.conf

RUN chmod +x /configure-esignet-ui-assets.sh \
    && /configure-esignet-ui-assets.sh

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
